### PR TITLE
Added a feature to allow logs to be sent to a custom cloudwatch endpoint, basically to a vpc endpoint.

### PR DESCRIPTION
**Pull request by harishmbm**
This will allow a custom vpc endpoint to be used if we want logs to not leave AWS environment

### CODE REVIEW

**Comment by harishmbm** [comment]
@pierredavidbelanger Kindly review this.

**Comment by pierredavidbelanger** [comment]
Interesting feature. I do it sometime for S3 or SQS locally with fakes3 or fakesqs. But I never had a usecase to change endpoint for CW Log myself.

Anyways, well done, thank you.

**Comment by hmoyal** [comment]
Thank you for the merge. We had a PCI requirement where we did not wanted logs to not leave AWS infrastructure so we investigated the library and did the tweak in code. Since you have merged it can we please know when this release version can be available to mvn central or similar repository so that we can use the official release version?

**Comment by harishmbm** [comment]
Thank you for the merge. We had a PCI requirement where we did not wanted logs to not leave AWS infrastructure so we investigated the library and did the tweak in code. Since you have merged it can we please know when this release version can be available to mvn central or similar repository so that we can use the official release version?

**Comment by pierredavidbelanger** [comment]
I [released a 1.3.0 version yesterday](/pierredavidbelanger/logback-awslogs-appender/commit/10520ae5a6e46ad1f5fddb6771495d8e1f016ad4).

It was available a couple of minutes later.

Sometime the [mvnrepository.com](https://mvnrepository.com/artifact/ca.pjer/logback-awslogs-appender) web site cache takes a long time to refresh. But the [1.3.0 release](https://repo1.maven.org/maven2/ca/pjer/logback-awslogs-appender/1.3.0/) was none the less available to the `mvn` command.

**Pull request merged**
