### PR TITLE
Add support for metrics

### PR DESCRIPTION
**Pull request by dnovitski**
This PR adds support for exposing awslogs appender metrics and some other minor improvements. An implementation for the metrics interface using Micrometer and Spring Boot can be found here: https://github.com/dnovitski/logback-awslogs-appender-metrics-micrometer

I'd love to get the micrometer implementation back upstream, give me a ping if you are interested!

### CODE REVIEW

**Comment by pierredavidbelanger** [comment]
Thank you for this PR, this is not bad at all, I really like this.

There is many thing going on though. I have some questions:

The new logStreamUuidPrefix config is optional right ? and the logStreamName have precedence ? 
Also, I guess someone could implement this using [a property defined on the fly](http://logback.qos.ch/manual/configuration.html#definingPropsOnTheFly).

I do not like de idea of the verbose "logging" directly to System.out, but I guess its nice to log when something do not work.

The idea behind AwsLogsMetrics/AwsLogsMetricsHolder is that a user can implements a custom AwsLogsMetrics then call AwsLogsMetricsHolder.set at the startup of his program to be able to collect metrics about this library behaviour, am I understanding correctly ?

**Comment by dnovitski** [comment]
Yeah, the logStreamUuidPrefix is optional. We're using ECS where many containers (of the same service) can start at the same time. To prevent any timestamp based collision UUID is the safer option.

I was having AccessDenied exceptions and stdout was the only place where I can see log output, so it definitely is handy when debugging issues. But once it works it can (and should) be turned off.

The idea behind AwsLogsMetricsHolder is exactly like you say. For a working example here is my micrometer implementation: https://github.com/dnovitski/logback-awslogs-appender-metrics-micrometer/blob/master/src/main/java/ca/pjer/logback/metrics/micrometer/instrument/AwsLogsMetricsMeter.java

**Comment by dnovitski** [comment]
If you'd like me to split into seperate PR's, let me know. I've been adjusting the project a bit to our needs, would love to get it all upstreamed

**Comment by pierredavidbelanger** [comment]
I merged as is, bumped to 1.4.0 then released to maven central, it should be available soon

Thank you!

**Comment by dnovitski** [comment]
Great, thanks!

**Pull request merged**
